/**
 * Postgres connection + Drizzle handle. The driver is chosen at boot from env
 * (see `db/index.ts` note in the migration blueprint):
 *
 *   - `DATABASE_URL` SET   → postgres-js against Supabase (hosted prod/staging).
 *                            `prepare:false` is REQUIRED for the pgBouncer
 *                            transaction pooler (`:6543`).
 *   - `DATABASE_URL` UNSET → embedded pglite, file-backed at `<dataDir>/pgdata`
 *                            (local dev + light self-host + tests). Same pg
 *                            dialect, same migrations, zero external database.
 *
 * `store.ts` is single-sourced across both — the drizzle query-builder API is
 * identical; only this file branches. A `globalThis` guard keeps the handle a
 * true singleton across dev HMR reloads (the Scheduler shares it in-process).
 *
 * Migrations live in `packages/server/drizzle` (generated by drizzle-kit). In
 * the HOSTED tier they're applied out-of-process via `pnpm db:migrate` before
 * `start` (over the DIRECT `:5432` URL); `runMigrations()` also applies them
 * in-process (the pglite tier's only path, plus dev boot + tests).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { PGlite } from "@electric-sql/pglite";
import { drizzle as drizzlePglite, type PgliteDatabase } from "drizzle-orm/pglite";
import { drizzle as drizzlePostgres, type PostgresJsDatabase } from "drizzle-orm/postgres-js";
import postgres, { type Sql } from "postgres";

import { dataDir, databaseUrl, directDatabaseUrl } from "../env.js";
import { machines, loops, runs, teams, teamMembers, notificationChannels, blobs, artifactFiles } from "./schema.js";
import { user, session, account, verification } from "./auth-schema.js";

// Business tables + Better Auth tables share one Drizzle instance (the auth
// drizzleAdapter reads its tables from here).
const schema = {
  machines,
  loops,
  runs,
  teams,
  teamMembers,
  notificationChannels,
  blobs,
  artifactFiles,
  user,
  session,
  account,
  verification,
};

// The postgres-js handle is the canonical type; the pglite handle exposes an
// identical query-builder surface and is cast to it (runtime-safe — the drivers
// differ only in the underlying result HKT, never the builder API store.ts uses).
type Db = PostgresJsDatabase<typeof schema>;
type Driver = "postgres" | "pglite";
type Client = Sql | PGlite;

const g = globalThis as unknown as { __loopanyDb?: Db; __loopanyClient?: Client; __loopanyDriver?: Driver };

function open(): { db: Db; client: Client; driver: Driver } {
  if (g.__loopanyDb && g.__loopanyClient && g.__loopanyDriver) {
    return { db: g.__loopanyDb, client: g.__loopanyClient, driver: g.__loopanyDriver };
  }
  const url = databaseUrl();
  if (url) {
    // Hosted tier: postgres-js against Supabase. `prepare:false` is mandatory for
    // the pgBouncer transaction pooler (:6543) — cached prepared statements break.
    const client = postgres(url, { prepare: false });
    const db = drizzlePostgres(client, { schema });
    g.__loopanyClient = client;
    g.__loopanyDb = db;
    g.__loopanyDriver = "postgres";
    return { db, client, driver: "postgres" };
  }
  // Embedded tier: file-backed pglite (WASM Postgres) at <dataDir>/pgdata.
  const dir = path.join(dataDir(), "pgdata");
  fs.mkdirSync(dataDir(), { recursive: true });
  const client = new PGlite(dir);
  const db = drizzlePglite(client, { schema }) as unknown as Db;
  g.__loopanyClient = client;
  g.__loopanyDb = db;
  g.__loopanyDriver = "pglite";
  return { db, client, driver: "pglite" };
}

const opened = open();
export const db: Db = opened.db;
/** Raw driver handle (postgres-js template tag OR the PGlite instance). Used by
 *  tests for low-level seeding/maintenance; app code always goes through `db`. */
export const client: Client = opened.client;

/** Migrations dir at the package root (resolved from this file: src/db → ../../drizzle). */
function migrationsDir(): string {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "drizzle");
}

/**
 * Apply generated migrations in-process (idempotent). The pglite tier's only
 * migration path; also dev boot + tests. The hosted tier ALSO applies them
 * out-of-process via `drizzle-kit migrate` on `start`, but this stays safe there
 * too — it runs DDL over a SEPARATE direct-URL client (never the pooler).
 */
export async function runMigrations(): Promise<void> {
  const dir = migrationsDir();
  if (!fs.existsSync(dir)) return; // not generated yet (pre-`db:generate`)
  if (opened.driver === "postgres") {
    const { migrate } = await import("drizzle-orm/postgres-js/migrator");
    const direct = directDatabaseUrl() ?? databaseUrl()!;
    // DDL + advisory lock must run over the DIRECT (:5432) connection, single-use.
    const migrationClient = postgres(direct, { max: 1 });
    try {
      await migrate(drizzlePostgres(migrationClient), { migrationsFolder: dir });
    } finally {
      await migrationClient.end();
    }
    return;
  }
  const { migrate } = await import("drizzle-orm/pglite/migrator");
  await migrate(opened.db as unknown as PgliteDatabase<typeof schema>, { migrationsFolder: dir });
}

export * from "./schema.js";
