/**
 * Postgres connection + Drizzle handle. The driver is chosen at boot from env
 * (see `db/index.ts` note in the migration blueprint):
 *
 *   - `DATABASE_URL` SET   → postgres-js against Supabase (hosted prod/staging).
 *                            `prepare:false` is REQUIRED for the pgBouncer
 *                            transaction pooler (`:6543`).
 *   - `DATABASE_URL` UNSET → embedded pglite, file-backed at `<dataDir>/pgdata`
 *                            (local dev + light self-host + tests). Same pg
 *                            dialect, same migrations, zero external database.
 *
 * `store.ts` is single-sourced across both — the drizzle query-builder API is
 * identical; only this file branches. A `globalThis` guard keeps the handle a
 * true singleton across dev HMR reloads (the Scheduler shares it in-process).
 *
 * Migrations live in `packages/server/drizzle` (generated by drizzle-kit). In
 * the HOSTED tier they're applied out-of-process via `pnpm db:migrate` before
 * `start` (over the DIRECT `:5432` URL); `runMigrations()` also applies them
 * in-process (the pglite tier's only path, plus dev boot + tests).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { PGlite } from "@electric-sql/pglite";
import { drizzle as drizzlePglite, type PgliteDatabase } from "drizzle-orm/pglite";
import { drizzle as drizzlePostgres, type PostgresJsDatabase } from "drizzle-orm/postgres-js";
import postgres, { type Sql } from "postgres";

import { dataDir, databaseUrl } from "../env.js";
import { logger } from "../logger.js";
import { machines, loops, runs, teams, teamMembers, teamInvites, notificationChannels, blobs, artifactFiles, runLeases, connectKeys } from "./schema.js";
import { user, session, account, verification } from "./auth-schema.js";

// Business tables + Better Auth tables share one Drizzle instance (the auth
// drizzleAdapter reads its tables from here).
const schema = {
  machines,
  loops,
  runs,
  teams,
  teamMembers,
  teamInvites,
  notificationChannels,
  blobs,
  artifactFiles,
  runLeases,
  connectKeys,
  user,
  session,
  account,
  verification,
};

// The postgres-js handle is the canonical type; the pglite handle exposes an
// identical query-builder surface and is cast to it (runtime-safe — the drivers
// differ only in the underlying result HKT, never the builder API store.ts uses).
type Db = PostgresJsDatabase<typeof schema>;
type Driver = "postgres" | "pglite";
type Client = Sql | PGlite;

const g = globalThis as unknown as { __loopanyDb?: Db; __loopanyClient?: Client; __loopanyDriver?: Driver };

/** Host (host:port, NEVER credentials) of a Postgres URL, for boot logging. */
function pgHost(url: string): string {
  try {
    return new URL(url).host || "unknown";
  } catch {
    return "unparseable";
  }
}

function open(): { db: Db; client: Client; driver: Driver } {
  if (g.__loopanyDb && g.__loopanyClient && g.__loopanyDriver) {
    return { db: g.__loopanyDb, client: g.__loopanyClient, driver: g.__loopanyDriver };
  }
  const url = databaseUrl();
  if (url) {
    // Hosted tier: postgres-js against Supabase. `prepare:false` is mandatory for
    // the pgBouncer transaction pooler (:6543) — cached prepared statements break.
    // Log the HOST only — never the full URL (it carries the password).
    logger.info({ tier: "postgres", host: pgHost(url) }, "database tier: postgres");
    // A URL with no sslmode may negotiate a PLAINTEXT connection. A local dev
    // Postgres is a legitimate no-SSL case, so warn loudly rather than hard-fail.
    if (!/sslmode=/i.test(url)) {
      logger.warn(
        { host: pgHost(url) },
        "DATABASE_URL has no sslmode — the connection may be plaintext; append ?sslmode=require",
      );
    }
    // Conservative pool for one always-on machine against the pooler. `max_lifetime`
    // + `statement_timeout` are the pool's self-healing ring after the 2026-07-09
    // wedged-pool incident (see api.health.db.ts for the full story + Fly backstop).
    const client = postgres(url, {
      prepare: false,
      max: 10,
      idle_timeout: 30,
      connect_timeout: 15,
      max_lifetime: 60 * 30, // 30 min — retire connections by age so dead sockets drop
      connection: { statement_timeout: 30_000 }, // 30s server-side kill for a hung query (ms)
    });
    const db = drizzlePostgres(client, { schema });
    g.__loopanyClient = client;
    g.__loopanyDb = db;
    g.__loopanyDriver = "postgres";
    return { db, client, driver: "postgres" };
  }
  // Embedded tier: file-backed pglite (WASM Postgres) at <dataDir>/pgdata.
  // Fail HARD in production unless the ephemeral embedded DB is opted into
  // explicitly — a missing DATABASE_URL secret must NOT silently boot an empty
  // pglite on ephemeral disk (data loss on the next redeploy).
  if (process.env.NODE_ENV === "production" && process.env.LOOPANY_DB !== "pglite") {
    throw new Error(
      "refusing to boot the ephemeral embedded database in production — " +
        "set DATABASE_URL, or LOOPANY_DB=pglite to opt in",
    );
  }
  const dir = path.join(dataDir(), "pgdata");
  logger.info({ tier: "pglite", pgdata: dir }, "database tier: pglite");
  fs.mkdirSync(dataDir(), { recursive: true });
  const client = new PGlite(dir);
  const db = drizzlePglite(client, { schema }) as unknown as Db;
  g.__loopanyClient = client;
  g.__loopanyDb = db;
  g.__loopanyDriver = "pglite";
  return { db, client, driver: "pglite" };
}

const opened = open();
export const db: Db = opened.db;
/** Raw driver handle (postgres-js template tag OR the PGlite instance). Used by
 *  tests for low-level seeding/maintenance; app code always goes through `db`. */
export const client: Client = opened.client;

/**
 * Migrations dir. In DEV this file lives at `src/db`, so the folder is at the
 * package root (`../../drizzle`). In the BUILT server the module is bundled under
 * `.output/server/{_ssr,_libs}` and `copy-pglite-assets.mjs` lands the folder at
 * `.output/server/drizzle` (`../drizzle`). Return the first candidate that exists
 * so the embedded pglite tier migrates in-process from either layout.
 */
function migrationsDir(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const devDir = path.resolve(here, "..", "..", "drizzle"); // dev: src/db → package root
  const builtDir = path.resolve(here, "..", "drizzle"); // built: .output/server/{_ssr,_libs} → .output/server/drizzle
  if (fs.existsSync(devDir)) return devDir;
  if (fs.existsSync(builtDir)) return builtDir;
  return devDir;
}

/**
 * Apply generated migrations IN-PROCESS (idempotent). This is the PGLITE tier's
 * only migration path (also dev boot + tests). The HOSTED postgres tier is a
 * NO-OP here: `prestart.mjs` (and `pnpm db:migrate`) own hosted migrations, run
 * once out-of-process over the DIRECT (:5432) URL before serving — re-migrating
 * over a second connection on every boot only risks a wedged connection hanging
 * boot and double-running the advisory lock.
 */
export async function runMigrations(): Promise<void> {
  if (opened.driver === "postgres") return; // hosted tier migrates in prestart.mjs
  const dir = migrationsDir();
  if (!fs.existsSync(dir)) return; // not generated yet (pre-`db:generate`)
  const { migrate } = await import("drizzle-orm/pglite/migrator");
  await migrate(opened.db as unknown as PgliteDatabase<typeof schema>, { migrationsFolder: dir });
}

/**
 * Best-effort clean shutdown of the runtime postgres pool (called from the boot
 * AbortController on SIGINT/SIGTERM). No-op for pglite (its file handle closes
 * with the process). Never throws — shutdown must not wedge on a slow drain.
 */
export async function closeClient(): Promise<void> {
  if (opened.driver !== "postgres") return;
  try {
    await (opened.client as Sql).end({ timeout: 5 });
  } catch {
    // ignore — process is exiting
  }
}

export * from "./schema.js";
