/**
 * SQLite connection + Drizzle handle. Single better-sqlite3 instance (WAL,
 * foreign keys on) opened against the data dir / Fly volume. A `globalThis`
 * guard keeps it a true singleton across dev HMR reloads (the Scheduler shares
 * this same connection in-process).
 *
 * Migrations live in `packages/server/drizzle` (generated by drizzle-kit). In
 * prod they're applied out-of-process via `pnpm db:migrate` before `start`;
 * `runMigrations()` also applies them in-process (used by dev boot + tests).
 * Single instance, so no migration-lock dance.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Database from "better-sqlite3";
import { drizzle, type BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";

import { dbPath } from "../env.js";
import { machines, loops, runs, teams, teamMembers, notificationChannels, blobs, artifactFiles } from "./schema.js";
import { user, session, account, verification } from "./auth-schema.js";

// Business tables + Better Auth tables share one Drizzle instance (the auth
// drizzleAdapter reads its tables from here).
const schema = {
  machines,
  loops,
  runs,
  teams,
  teamMembers,
  notificationChannels,
  blobs,
  artifactFiles,
  user,
  session,
  account,
  verification,
};

type Db = BetterSQLite3Database<typeof schema>;

const g = globalThis as unknown as { __loopanyDb?: Db; __loopanySqlite?: Database.Database };

function open(): { db: Db; sqlite: Database.Database } {
  if (g.__loopanyDb && g.__loopanySqlite) return { db: g.__loopanyDb, sqlite: g.__loopanySqlite };
  const file = dbPath();
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const sqlite = new Database(file);
  sqlite.pragma("journal_mode = WAL");
  sqlite.pragma("foreign_keys = ON");
  const db = drizzle(sqlite, { schema });
  g.__loopanySqlite = sqlite;
  g.__loopanyDb = db;
  return { db, sqlite };
}

const opened = open();
export const db: Db = opened.db;
/** Raw better-sqlite3 handle (for migrations + low-level maintenance). */
export const sqlite: Database.Database = opened.sqlite;

/** Migrations dir at the package root (resolved from this file: src/db → ../../drizzle). */
function migrationsDir(): string {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "drizzle");
}

/** Apply generated migrations in-process (idempotent). Dev boot + tests. */
export function runMigrations(): void {
  const dir = migrationsDir();
  if (!fs.existsSync(dir)) return; // not generated yet (pre-`db:generate`)
  migrate(db, { migrationsFolder: dir });
}

export * from "./schema.js";
