import { createFileRoute } from "@tanstack/react-router";
import { resolveApiContext } from "../kernel/apiAuth.js";
import { objectArtifact, replaceFromArtifact, showObject } from "../kernel/objectApi.js";
import * as store from "../db/kernelStore.js";
import { apiResponse, authFailure, rawArtifact } from "../kernel/routeSupport.js";
import { refusal, refusalResponse } from "../kernel/refusals.js";
export const Route = createFileRoute("/api/docs/$docId")({ server: { handlers: {
  GET: async ({ request, params }: { request: Request; params: { docId: string } }) => { const auth = await resolveApiContext(request, "dual"); if (!auth.ok) return authFailure(auth.error); const accept = request.headers.get("accept") ?? "application/json"; if (accept.includes("text/markdown")) { const row = await store.getObject(undefined, params.docId); if (!row || row.teamId !== auth.context.teamId) return refusalResponse(refusal("NOT_FOUND", `${params.docId} was not found`)); if (row.kind !== "doc") return refusalResponse(refusal("WRONG_KIND", `${params.docId} is a ${row.kind}, not a doc`)); return new Response(objectArtifact(row), { headers: { "Content-Type": "text/markdown; charset=utf-8" } }); } if (!accept.includes("application/json") && accept !== "*/*") return refusalResponse(refusal("INVALID_BODY", "Accept must allow application/json or text/markdown"), { status: 406 }); const eventLimit = Number(new URL(request.url).searchParams.get("events") ?? 20); if (!Number.isInteger(eventLimit) || eventLimit < 0 || eventLimit > 200) return refusalResponse(refusal("UNKNOWN_FILTER", "events must be an integer from 0 to 200")); return apiResponse(await showObject("doc", params.docId, auth.context, eventLimit)); },
  PATCH: async ({ request, params }: { request: Request; params: { docId: string } }) => { const auth = await resolveApiContext(request, "dual", true); if (!auth.ok) return authFailure(auth.error); const raw = await rawArtifact(request); return raw.ok ? apiResponse(await replaceFromArtifact("doc", params.docId, raw.text, auth.context)) : raw.response; },
} } });
