/**
 * Best-effort local install of the loopany agent skill via the `npx skills` CLI
 * (vercel-labs/skills). Installed at USER scope to match the daemon's per-machine
 * scope: coding agents discover user-level skills from ANY workdir, so a loop agent
 * still triggers the create/update/evolve references no matter where it runs — no
 * per-workdir copies scattering. It's fired at `loopany up` (refreshing the install
 * to whatever daemon version just launched) and again after a successful
 * `loopany new`, and it NEVER blocks: any failure (no network, no npx, no write
 * permission, bundled skill absent) degrades silently to the always-working
 * /api/skill inline path. It just prints one status line. `loopany skill install`
 * is the manual escape hatch (`--project` installs into the cwd instead).
 *
 * MULTI-AGENT: the skill is installed for every coding agent loopany knows about
 * (`SKILL_TARGET_AGENTS` — currently Claude Code and Codex, the two `CodingAgent`
 * values), so a Codex user (or any of the two) gets the skill, not just Claude Code.
 * We deliberately DON'T pass `-a '*'`: empirically the `skills` CLI treats `'*'` as
 * "install to ALL ~72 supported agents regardless of presence", littering dozens of
 * home dirs (`~/.aider-desk`, `~/.astrbot`, …). Targeting the known agents explicitly
 * stays clean and is trivially extendable (add an entry to `SKILL_TARGET_AGENTS`).
 * NOTE: the comma form `-a claude-code,codex` is INVALID (the CLI parses it as a
 * single agent name); the list must be passed as repeated `-a <agent>` flags.
 *
 * (History: 0.4.0 deliberately kept skill logic OUT of `up` because project scope
 * would pollute an arbitrary cwd; the flip to user scope removes that hazard, so
 * `up` is now the natural refresh point — version-locked to the daemon it launches.)
 *
 * We install from the skill BUNDLED INTO THIS PACKAGE (synced from
 * packages/server/src/skill/ by scripts/sync-skill.mjs at build/prepublish) — a
 * LOCAL path source, so end users never need the private platform repo and the
 * install works offline once `skills` itself is cached. The exact invocation
 *   npx --yes skills add <dir> -a claude-code -a codex -y --copy -g
 * was verified against the current `skills` CLI (`-g` targets each agent's user dir
 * → ~/.claude/skills/loopany/ for Claude Code, ~/.agents/skills/loopany/ for Codex;
 * `-y` is non-interactive + idempotent-overwrite; `--copy` makes a self-contained
 * copy, no symlink into this package's temp dir). Dropping `-g` (the `--project`
 * escape hatch) installs into the runner's cwd instead.
 *
 * CAVEAT: a PRE-EXISTING per-workdir skill copy left behind by the old project-scope
 * installer is NOT auto-removed — it must be deleted BY HAND, or it shadows the
 * user-level skill (project scope wins in agent discovery).
 */
import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const moduleDir = path.dirname(fileURLToPath(import.meta.url));

/** Hard ceiling on the `npx skills` call so a hung install can't wedge `loopany new`. */
const INSTALL_TIMEOUT_MS = 90_000;

/**
 * A SKILL this CLI can install. There are exactly two and they are STRICTLY
 * separate distributions — installing one can never touch the other, because they
 * differ in the only thing the `skills` CLI keys on: the SKILL.md front-matter
 * `name`, which is also the directory it lands in.
 *
 *   loopany      — the shipping product's skill (create/update/evolve/run loops).
 *                  Synced from packages/server/src/skill/ by sync-skill.mjs into
 *                  the gitignored `skill/`, and SHIPPED in the npm tarball.
 *   loopany-dev  — the REWRITE (kernel) flow's skill. Authored directly in the
 *                  repo under `skill-dev/` and deliberately NOT in package.json
 *                  `files`, so it never rides the tarball to end users: it teaches
 *                  a LOCAL dev stack, and shipping it would put dev-stack
 *                  instructions on production machines.
 */
export interface SkillPackage {
  /** The installed skill's name — the dir agents discover it under, and what the
   *  `skills` CLI reads from the bundled SKILL.md front matter. */
  name: string;
  /** The package-relative directory holding this skill's source. */
  dir: string;
  /** The prefix of the one status line an install prints. */
  tag: string;
}

export const PROD_SKILL: SkillPackage = { name: "loopany", dir: "skill", tag: "loopany skill" };
export const DEV_SKILL: SkillPackage = { name: "loopany-dev", dir: "skill-dev", tag: "loopany skill (loopany-dev)" };

/**
 * The skill dir bundled into this package. `../<dir>` resolves the same from both
 * `src/` (tsx dev) and `dist/` (built) since each sits beside the package-root
 * dir. The prod one is generated by scripts/sync-skill.mjs and is absent in a
 * source-only checkout that was never built; the dev one is absent in an npm
 * install (it is not in `files`). Either way the install best-effort-skips.
 */
export function bundledSkillDir(base = moduleDir, skill: SkillPackage = PROD_SKILL): string {
  return path.join(base, "..", skill.dir);
}

/** The `loopany-dev` skill's source dir, authored in this repo (not generated). */
export function bundledDevSkillDir(base = moduleDir): string {
  return bundledSkillDir(base, DEV_SKILL);
}

/** Whether the bundled skill is actually present (its SKILL.md exists). */
export function bundledSkillAvailable(dir = bundledSkillDir()): boolean {
  try {
    return fs.statSync(path.join(dir, "SKILL.md")).isFile();
  } catch {
    return false;
  }
}

export interface InstallOutcome {
  ok: boolean;
  /** One human-facing line to print (announced, best-effort). */
  line: string;
}

/** Result of running the installer command. Injected in tests so no network/npx. */
export interface RunResult {
  code: number;
  stdout: string;
  stderr: string;
}
export type Runner = (cmd: string, args: string[], opts?: { cwd?: string }) => Promise<RunResult>;

/** Spawn `npx skills …`, capture output, bounded by INSTALL_TIMEOUT_MS. Resolves
 *  (never rejects) with code -1 when the binary can't be spawned or times out. The
 *  child's `cwd` decides where a project-level install lands (`<cwd>/.claude/…`). */
const defaultRunner: Runner = (cmd, args, opts) =>
  new Promise<RunResult>((resolve) => {
    let stdout = "";
    let stderr = "";
    let child;
    try {
      child = spawn(cmd, args, { stdio: ["ignore", "pipe", "pipe"], cwd: opts?.cwd });
    } catch (err) {
      resolve({ code: -1, stdout: "", stderr: err instanceof Error ? err.message : String(err) });
      return;
    }
    const timer = setTimeout(() => {
      try {
        child.kill("SIGKILL");
      } catch {
        /* already gone */
      }
    }, INSTALL_TIMEOUT_MS);
    timer.unref?.();
    child.stdout?.on("data", (d) => (stdout += String(d)));
    child.stderr?.on("data", (d) => (stderr += String(d)));
    child.on("error", (err) => {
      clearTimeout(timer);
      resolve({ code: -1, stdout, stderr: err instanceof Error ? err.message : String(err) });
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve({ code: code ?? -1, stdout, stderr });
    });
  });

export interface InstallOpts {
  /** WHICH skill to install. Defaults to the shipping `loopany` one, so every
   *  existing caller (up / new / `loopany skill install`) is unchanged. */
  skill?: SkillPackage;
  /** Install to the user dir (`~/.claude/skills`) instead of the project default. */
  global?: boolean;
  /** Project-level install target: the dir to run `npx skills` in, so the skill
   *  lands in `<cwd>/.claude/skills/loopany`. Defaults to the process cwd. Ignored
   *  when `global` is set (that always targets `~/.claude/skills`). */
  cwd?: string;
  /** Override the bundled skill dir (tests). */
  dir?: string;
  /** Override the command runner (tests) so nothing spawns npx / hits the network. */
  runner?: Runner;
}

/**
 * The coding agents the loopany skill install targets — the two `CodingAgent`
 * values. Each carries the `skills` CLI agent id (for `-a <id>`), a human label,
 * and the skill dir layout that agent reads (relative to the scope root: `~` for a
 * global/user install, the cwd for a project install). Verified empirically against
 * the current `skills` CLI: Claude Code reads `.claude/skills`, Codex reads the
 * universal `.agents/skills`. Extend this list to cover a new agent (installArgs and
 * `loopany skill status` both derive from it — they cannot drift).
 */
export const SKILL_TARGET_AGENTS: ReadonlyArray<{
  id: string;
  label: string;
  /** Path segments under the scope root, before the `loopany` skill dir. */
  skillsRoot: readonly string[];
}> = [
  { id: "claude-code", label: "Claude Code", skillsRoot: [".claude", "skills"] },
  { id: "codex", label: "Codex", skillsRoot: [".agents", "skills"] },
];

/** The argv (after `npx`) for the install — pure, so tests can assert it. Targets
 *  every agent in `SKILL_TARGET_AGENTS` via repeated `-a <id>` flags (the comma form
 *  `-a a,b` is rejected by the CLI as one bogus agent name). */
export function installArgs(dir: string, global = false): string[] {
  const args = ["--yes", "skills", "add", dir];
  for (const t of SKILL_TARGET_AGENTS) args.push("-a", t.id);
  args.push("-y", "--copy");
  if (global) args.push("-g");
  return args;
}

/** The per-agent skill directories a given scope install writes to, for display.
 *  `global` → under `~`; else under `cwd` (or `.` when unset, keeping the `./` prefix
 *  path.join would otherwise strip). The leaf is the SKILL's name, which is what
 *  keeps `loopany-dev` in its own directory beside `loopany`, never over it. */
export function targetSkillDirs(opts: { global?: boolean; cwd?: string; skill?: SkillPackage } = {}): string[] {
  const name = (opts.skill ?? PROD_SKILL).name;
  return SKILL_TARGET_AGENTS.map((t) => {
    if (opts.global) return path.join("~", ...t.skillsRoot, name);
    if (opts.cwd) return path.join(opts.cwd, ...t.skillsRoot, name);
    return `./${path.join(...t.skillsRoot, name)}`;
  });
}

/**
 * Install/refresh the loopany skill. NEVER throws — returns an outcome with a
 * one-line status to print. Idempotent: `skills add -y` overwrites an existing
 * install with the bundled (current) content every time.
 */
export async function installSkill(opts: InstallOpts = {}): Promise<InstallOutcome> {
  const skill = opts.skill ?? PROD_SKILL;
  const dir = opts.dir ?? bundledSkillDir(moduleDir, skill);
  if (!bundledSkillAvailable(dir)) {
    return {
      ok: false,
      line: `${skill.tag}: skipped (bundled skill not found — falling back to /api/skill)`,
    };
  }
  const runner = opts.runner ?? defaultRunner;
  // A project install runs in `cwd` (so it lands there); a global one ignores it.
  const cwd = opts.global ? undefined : opts.cwd;
  let res: RunResult;
  try {
    res = await runner("npx", installArgs(dir, opts.global), { cwd });
  } catch (err) {
    return { ok: false, line: `${skill.tag}: skipped (${err instanceof Error ? err.message : String(err)})` };
  }
  if (res.code === 0) {
    const where = targetSkillDirs(opts).join(", ");
    return { ok: true, line: `${skill.tag}: installed → ${where}` };
  }
  const why = firstLine(res.stderr) || firstLine(res.stdout) || `exit ${res.code}`;
  return { ok: false, line: `${skill.tag}: skipped (${why}) — falling back to /api/skill` };
}

function firstLine(s: string): string {
  return (s || "").trim().split("\n")[0]?.trim() ?? "";
}
