/**
 * Best-effort local install of the loopany agent skill via the `npx skills` CLI
 * (vercel-labs/skills). Called from `loopany new` once a loop is successfully
 * created, targeting that loop's own workdir (the dir its agent runs in), so the
 * user's coding agent discovers the create/update/evolve references natively there
 * — but it NEVER blocks loop creation: any failure (no network, no npx, no write
 * permission, bundled skill absent) degrades silently to the always-working
 * /api/skill inline path. It just prints one status line. `loopany skill install`
 * is the manual escape hatch for installing it by hand anywhere.
 *
 * We install from the skill BUNDLED INTO THIS PACKAGE (synced from
 * packages/server/src/skill/ by scripts/sync-skill.mjs at build/prepublish) — a
 * LOCAL path source, so end users never need the private platform repo and the
 * install works offline once `skills` itself is cached. The exact invocation
 *   npx --yes skills add <dir> -a claude-code -y --copy
 * was verified against the current `skills` CLI (project scope is the default →
 * ./.claude/skills/loopany/; `-y` is non-interactive + idempotent-overwrite;
 * `--copy` makes a self-contained copy, no symlink into this package's temp dir).
 */
import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const moduleDir = path.dirname(fileURLToPath(import.meta.url));

/** Hard ceiling on the `npx skills` call so a hung install can't wedge `loopany up`. */
const INSTALL_TIMEOUT_MS = 90_000;

/**
 * The skill dir bundled into this package. `../skill` resolves the same from both
 * `src/` (tsx dev) and `dist/` (built) since each sits beside the package-root
 * `skill/`. Generated by scripts/sync-skill.mjs; absent in a source-only checkout
 * that was never built (then install best-effort-skips).
 */
export function bundledSkillDir(base = moduleDir): string {
  return path.join(base, "..", "skill");
}

/** Whether the bundled skill is actually present (its SKILL.md exists). */
export function bundledSkillAvailable(dir = bundledSkillDir()): boolean {
  try {
    return fs.statSync(path.join(dir, "SKILL.md")).isFile();
  } catch {
    return false;
  }
}

export interface InstallOutcome {
  ok: boolean;
  /** One human-facing line to print (announced, best-effort). */
  line: string;
}

/** Result of running the installer command. Injected in tests so no network/npx. */
export interface RunResult {
  code: number;
  stdout: string;
  stderr: string;
}
export type Runner = (cmd: string, args: string[], opts?: { cwd?: string }) => Promise<RunResult>;

/** Spawn `npx skills …`, capture output, bounded by INSTALL_TIMEOUT_MS. Resolves
 *  (never rejects) with code -1 when the binary can't be spawned or times out. The
 *  child's `cwd` decides where a project-level install lands (`<cwd>/.claude/…`). */
const defaultRunner: Runner = (cmd, args, opts) =>
  new Promise<RunResult>((resolve) => {
    let stdout = "";
    let stderr = "";
    let child;
    try {
      child = spawn(cmd, args, { stdio: ["ignore", "pipe", "pipe"], cwd: opts?.cwd });
    } catch (err) {
      resolve({ code: -1, stdout: "", stderr: err instanceof Error ? err.message : String(err) });
      return;
    }
    const timer = setTimeout(() => {
      try {
        child.kill("SIGKILL");
      } catch {
        /* already gone */
      }
    }, INSTALL_TIMEOUT_MS);
    timer.unref?.();
    child.stdout?.on("data", (d) => (stdout += String(d)));
    child.stderr?.on("data", (d) => (stderr += String(d)));
    child.on("error", (err) => {
      clearTimeout(timer);
      resolve({ code: -1, stdout, stderr: err instanceof Error ? err.message : String(err) });
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve({ code: code ?? -1, stdout, stderr });
    });
  });

export interface InstallOpts {
  /** Install to the user dir (`~/.claude/skills`) instead of the project default. */
  global?: boolean;
  /** Project-level install target: the dir to run `npx skills` in, so the skill
   *  lands in `<cwd>/.claude/skills/loopany`. Defaults to the process cwd. Ignored
   *  when `global` is set (that always targets `~/.claude/skills`). */
  cwd?: string;
  /** Override the bundled skill dir (tests). */
  dir?: string;
  /** Override the command runner (tests) so nothing spawns npx / hits the network. */
  runner?: Runner;
}

/** The argv (after `npx`) for the install — pure, so tests can assert it. */
export function installArgs(dir: string, global = false): string[] {
  const args = ["--yes", "skills", "add", dir, "-a", "claude-code", "-y", "--copy"];
  if (global) args.push("-g");
  return args;
}

/**
 * Install/refresh the loopany skill. NEVER throws — returns an outcome with a
 * one-line status to print. Idempotent: `skills add -y` overwrites an existing
 * install with the bundled (current) content every time.
 */
export async function installSkill(opts: InstallOpts = {}): Promise<InstallOutcome> {
  const dir = opts.dir ?? bundledSkillDir();
  if (!bundledSkillAvailable(dir)) {
    return {
      ok: false,
      line: "loopany skill: skipped (bundled skill not found — falling back to /api/skill)",
    };
  }
  const runner = opts.runner ?? defaultRunner;
  // A project install runs in `cwd` (so it lands there); a global one ignores it.
  const cwd = opts.global ? undefined : opts.cwd;
  let res: RunResult;
  try {
    res = await runner("npx", installArgs(dir, opts.global), { cwd });
  } catch (err) {
    return { ok: false, line: `loopany skill: skipped (${err instanceof Error ? err.message : String(err)})` };
  }
  if (res.code === 0) {
    const where = opts.global
      ? "~/.claude/skills/loopany"
      : opts.cwd
        ? path.join(opts.cwd, ".claude", "skills", "loopany")
        : "./.claude/skills/loopany";
    return { ok: true, line: `loopany skill: installed → ${where}` };
  }
  const why = firstLine(res.stderr) || firstLine(res.stdout) || `exit ${res.code}`;
  return { ok: false, line: `loopany skill: skipped (${why}) — falling back to /api/skill` };
}

function firstLine(s: string): string {
  return (s || "").trim().split("\n")[0]?.trim() ?? "";
}
